analytics: {}
color:
  brandColors:
    - '#101010'
    - '#6a5af9'
    - '#fefefe'
    - '#3b00c9'
    - '#aa8697'
  brandStrength: 0.5
  lightness: 0.75
  rhythmicContrast: 1
  saturation: 0.5
cta: {}
layout_spectrum: 0.001126
name: MUZAFFAR ALI
opengraph: {}
purpose: []
typography_spectrum: 0.82078
