name: MUZAFFAR ALI
favicon: null
layout_spectrum: 1
typography_spectrum: 0.84624
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#101010'
    - '#6a5af9'
    - '#fefefe'
    - '#3b00c9'
    - '#aa8697'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 0.375
  rhythmicContrast: 1
purpose: []
