name: MUZAFFAR ALI
favicon: null
layout_spectrum: 0.08265
typography_spectrum: 0.47901327535510063
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.4375
  lightness: 0.75
  saturation: 0.625
  rhythmicContrast: 1
purpose: []
