analytics: {}
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.4375
  lightness: 0.75
  rhythmicContrast: 1
  saturation: 0.625
cta: {}
layout_spectrum: 0.581081
name: MUZAFFAR ALI
opengraph: {}
purpose: []
typography_spectrum: 0.84624
